version: '3'
services:
  webserver:
    image: blockchain-web:latest
    build:
      context: web
      dockerfile: Dockerfile
    tty: true
    links:
      - blockchain
    expose:
      - 4000
    ports:
      - 4000:4000

  blockchain:
    image: blockchain:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    expose:
      - 6000
    ports:
      - 6000
