// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package blockchain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	VAL                  int64    `protobuf:"varint,3,opt,name=VAL" json:"VAL,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=Hash" json:"Hash,omitempty"`
	PrevHash             string   `protobuf:"bytes,5,opt,name=PrevHash" json:"PrevHash,omitempty"`
	Difficulty           int64    `protobuf:"varint,6,opt,name=Difficulty" json:"Difficulty,omitempty"`
	Nonce                string   `protobuf:"bytes,7,opt,name=Nonce" json:"Nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_559f7e5beaa762d0, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Block) GetVAL() int64 {
	if m != nil {
		return m.VAL
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *Block) GetDifficulty() int64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *Block) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type BlockRequest struct {
	Index                int64    `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_559f7e5beaa762d0, []int{1}
}
func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (dst *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(dst, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "blockchain.Block")
	proto.RegisterType((*BlockRequest)(nil), "blockchain.BlockRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BookService service

type BookServiceClient interface {
	GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*Block, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetBlock(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := grpc.Invoke(ctx, "/blockchain.BookService/GetBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceServer interface {
	GetBlock(context.Context, *BlockRequest) (*Block, error)
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.BookService/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBlock(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _BookService_GetBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_559f7e5beaa762d0) }

var fileDescriptor_example_559f7e5beaa762d0 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xca, 0xc9, 0x4f, 0xce,
	0x4e, 0xce, 0x48, 0xcc, 0xcc, 0x53, 0xda, 0xcc, 0xc8, 0xc5, 0xea, 0x04, 0xe2, 0x0a, 0x89, 0x70,
	0xb1, 0x7a, 0xe6, 0xa5, 0xa4, 0x56, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x38, 0x42,
	0x32, 0x5c, 0x9c, 0x21, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x12, 0x4c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21, 0x01, 0x2e, 0xe6, 0x30, 0x47, 0x1f, 0x09, 0x66, 0xb0, 0x0e,
	0x10, 0x53, 0x48, 0x88, 0x8b, 0xc5, 0x23, 0xb1, 0x38, 0x43, 0x82, 0x05, 0xac, 0x14, 0xcc, 0x16,
	0x92, 0xe2, 0xe2, 0x08, 0x28, 0x4a, 0x2d, 0x03, 0x8b, 0xb3, 0x82, 0xc5, 0xe1, 0x7c, 0x21, 0x39,
	0x2e, 0x2e, 0x97, 0xcc, 0xb4, 0xb4, 0xcc, 0xe4, 0xd2, 0x9c, 0x92, 0x4a, 0x09, 0x36, 0xb0, 0x41,
	0x48, 0x22, 0x20, 0x57, 0xf9, 0xe5, 0xe7, 0x25, 0xa7, 0x4a, 0xb0, 0x83, 0x35, 0x42, 0x38, 0x4a,
	0x2a, 0x5c, 0x3c, 0x60, 0x47, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x60, 0x77, 0xbb, 0x91,
	0x07, 0x17, 0xb7, 0x53, 0x7e, 0x7e, 0x76, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x25,
	0x17, 0x87, 0x7b, 0x6a, 0x09, 0xc4, 0xb3, 0x12, 0x7a, 0x88, 0x30, 0xd0, 0x43, 0x36, 0x4a, 0x4a,
	0x10, 0x43, 0x46, 0x89, 0xc1, 0x89, 0x27, 0x0a, 0x29, 0xcc, 0x92, 0xd8, 0xc0, 0xc1, 0x68, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x86, 0x9d, 0xee, 0x78, 0x57, 0x01, 0x00, 0x00,
}